language: python
python:
  - "3.4"
addons:
  postgresql: "9.3"
before_script:
  - createdb accountable_db
install:
  - pip install tox coveralls
env:
  - TOX_ENV=tests
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
